version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    volumes:
      - ./data:/data/db
    restart: unless-stopped
  remindmebot:
    build: ./app
    container_name: remindmebot
    hostname: remindmebot
    environment:
      - dbUrl=mongodb:27017/remindmebot
    restart: unless-stopped
    .depends_on:
      - mongodb
    volumes:
      - ./appstate.json:/usr/src/app/appstate.json
